### ISSUE TITLE
Parameterized asyncUI

### ISSUE THREAD

**Issue by okkero** [nhaarman/AsyncAwait-Android#10]
There should be an `asyncUI<T>`  function. I need to run an asyncUI task that also returns a result.

**Comment by nhaarman** [comment]
Can you give an example of a use case?

**Comment by okkero** [comment]
Mhm. Say I have an asyncUI method awaiting some async tasks, and returning to the UI thread to do stuff after each async task. Now, say I want this method to return a result, and another async to await its result.

You can find this implemented in C# with `Task<TResult>`, and I'm under the impression that this lib is inspired by C#'s async/await.

**Comment by okkero** [comment]
Thank you for implementing this :)
